import os
import warnings

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from dotenv import load_dotenv
from fpdf import FPDF
from google import genai
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller

load_dotenv()
warnings.filterwarnings("ignore")
sns.set_theme(style="whitegrid")


class AirRaidAnalyzer:
    """
    A class for analyzing air raid alarm time series in Ukraine and generating reports using AI.
    """

    def __init__(self, alerts_path: str, risk_path: str, gemini_api_key: str):
        # --- File Paths ---
        self.alerts_path = (
            alerts_path  # Path to the CSV file containing detailed air raid alert logs
        )
        self.risk_path = risk_path  # Path to the CSV file containing regional risk and load statistics

        # --- DataFrames (Initialized as None) ---
        self.df_alerts = None  # Raw DataFrame for processed air raid alert logs
        self.df_risk = None  # Raw DataFrame for regional risk data
        self.daily_alerts = (
            None  # Aggregated time series DataFrame (daily alert counts used for EDA)
        )

        # --- Report Storage ---
        self.metrics = (
            {}
        )  # Dictionary to store computed statistical metrics (e.g., total records, p-value)
        self.images_paths = (
            {}
        )  # Dictionary to store file paths of the generated PNG charts

        # --- AI Analytics Outputs ---
        # List storing 3 distinct text sections generated by the AI for each chart sequentially
        self.ai_analytics_parts = ["", "", ""]

        # --- Gemini API Configuration ---
        self.client = genai.Client(
            api_key=gemini_api_key
        )  # Initialized Google GenAI client instance
        self.model_name = (
            "gemini-3.5-flash"  # Name of the Gemini model used for text generation
        )

    def load_and_clean_data(self):
        # Load and clean data
        print("[1/7] Завантаження та очищення даних...")
        self.df_alerts = pd.read_csv(self.alerts_path)
        self.df_risk = pd.read_csv(self.risk_path)

        # Convert timestamps to datetime objects with UTC timezone
        self.df_alerts["started_at"] = pd.to_datetime(
            self.df_alerts["started_at"], utc=True
        )
        self.df_alerts["finished_at"] = pd.to_datetime(
            self.df_alerts["finished_at"], utc=True
        )

        # Calculate duration in minutes and filter out invalid records or outliers (> 24 hours)
        self.df_alerts["duration_min"] = (
            self.df_alerts["finished_at"] - self.df_alerts["started_at"]
        ).dt.total_seconds() / 60.0
        self.df_alerts = self.df_alerts[
            (self.df_alerts["duration_min"] >= 0)
            & (self.df_alerts["duration_min"] <= 1440)
        ]

        # Extract date from the start time for aggregation
        self.df_alerts["date"] = self.df_alerts["started_at"].dt.date
        self.metrics["total_records"] = len(self.df_alerts)

    def prepare_time_series(self):
        # Prepare daily time series
        print("[2/7] Формування часового ряду...")
        self.daily_alerts = (
            self.df_alerts.groupby("date").size().reset_index(name="alerts_count")
        )
        self.daily_alerts["date"] = pd.to_datetime(self.daily_alerts["date"])
        self.daily_alerts.set_index("date", inplace=True)

        # Reindex time series to fill missing dates with 0 alerts
        idx = pd.date_range(
            self.daily_alerts.index.min(), self.daily_alerts.index.max()
        )
        self.daily_alerts = self.daily_alerts.reindex(idx, fill_value=0)

        # Store general time series metadata into metrics dictionary
        self.metrics["start_date"] = self.daily_alerts.index.min().strftime("%Y-%m-%d")
        self.metrics["end_date"] = self.daily_alerts.index.max().strftime("%Y-%m-%d")
        self.metrics["max_daily"] = int(self.daily_alerts["alerts_count"].max())
        self.metrics["avg_daily"] = round(
            float(self.daily_alerts["alerts_count"].mean()), 1
        )

    def _save_plot_file(self, fig, name: str) -> str:
        # Save matplotlib figure to a temporary PNG file
        filename = f"tmp_chart_{name}.png"
        fig.savefig(filename, format="png", bbox_inches="tight", dpi=150)
        return filename

    def plot_eda(self):
        # --- Exploratory Data Analysis Plotting ---
        print("[3/7] Побудова графіків динаміки (EDA)...")
        fig, ax = plt.subplots(figsize=(14, 6))
        ax.plot(
            self.daily_alerts.index,
            self.daily_alerts["alerts_count"],
            color="gray",
            alpha=0.4,
            label="Щоденні тривоги",
        )
        # Plot 30-day rolling mean to illustrate the trend line
        ax.plot(
            self.daily_alerts.index,
            self.daily_alerts["alerts_count"].rolling(30).mean(),
            color="red",
            linewidth=2.5,
            label="Тренд (30 днів)",
        )

        ax.set_title("Динаміка кількості повітряних тривог в Україні", fontsize=16)
        ax.set_xlabel("Дата")
        ax.set_ylabel("Кількість")
        ax.legend()
        plt.tight_layout()

        self.images_paths["eda"] = self._save_plot_file(fig, "eda")
        # plt.show()
        plt.close(fig)

    def perform_decomposition(self):
        # --- Time Series Decomposition ---
        print("[4/7] Виконання статистичної декомпозиції...")
        decomp = seasonal_decompose(
            self.daily_alerts["alerts_count"], model="additive", period=30
        )
        fig = decomp.plot()
        fig.set_size_inches(14, 10)
        fig.axes[0].set_title(
            "Декомпозиція: Тренд, Сезонність та Випадковий Шум", fontsize=16
        )
        plt.tight_layout()

        self.images_paths["decomp"] = self._save_plot_file(fig, "decomp")
        # plt.show()
        plt.close(fig)

    def test_stationarity(self):
        # Augmented Dickey-Fuller Test
        print("[5/7] Проведення Тесту Дікі-Фуллера...")
        result = adfuller(self.daily_alerts["alerts_count"])
        p_value = result[1]
        self.metrics["adf_p_value"] = round(p_value, 4)
        self.metrics["is_stationary"] = p_value < 0.05
        print(
            f">>> p-value: {p_value:.4f} -> "
            f"{'Стаціонарний' if self.metrics['is_stationary'] else 'Нестаціонарний'}"
        )

    def plot_risk_profile(self):
        # --- Regional Risk Barplot ---
        print("[6/7] Аналіз профілю ризиків за регіонами...")
        top_regions = self.df_risk.sort_values(by="total_alerts", ascending=False).head(
            10
        )
        self.metrics["top_3_regions"] = ", ".join(
            top_regions["oblast"].head(3).tolist()
        )

        fig, ax = plt.subplots(figsize=(12, 6))
        sns.barplot(
            data=top_regions, x="total_alerts", y="oblast", palette="Reds_r", ax=ax
        )
        ax.set_title(
            "Топ-10 регіонів за загальним навантаженням (кількістю тривог)", fontsize=16
        )
        ax.set_xlabel("Загальна кількість тривог")
        ax.set_ylabel("")
        plt.tight_layout()

        self.images_paths["risk"] = self._save_plot_file(fig, "risk")
        # plt.show()
        plt.close(fig)

    def generate_ai_analytics(self):
        # Gemini AI Text Generation Pipeline
        print("[7/7] Генерація ІІ-аналітики через Gemini API...")

        # Constructing the instruction prompt for Gemini model in Ukrainian
        prompt = f"""
        Ти — військовий аналітик (Data Scientist), який пише звіт про повітряні тривоги в Україні.
        Проаналізуй наступні статистичні дані:
        - Період аналізу: з {self.metrics['start_date']} по {self.metrics['end_date']}
        - Загальна кількість тривог у вибірці: {self.metrics['total_records']}
        - Максимум тривог за день: {self.metrics['max_daily']}
        - Середня кількість за день: {self.metrics['avg_daily']}
        - Топ-3 найнебезпечніших регіони: {self.metrics['top_3_regions']}
        - Результат тесту Дікі-Фуллера (p-value): {self.metrics['adf_p_value']} (Стаціонарний: {self.metrics['is_stationary']}).

        Напиши короткий, професійний аналітичний звіт УКРАЇНСЬКОЮ мовою. 
        Розбий свою відповідь СТРОГО на 3 логічні частини. Встав між частинами роздільник "|||". 

        Часть 1: Опиши загальну динаміку (період, загальну кількість, середнє та максимуми).
        |||
        Часть 2: Прокоментуй декомпозицію та результати тесту Дікі-Фуллера (наявність трендів, стаціонарність ряду).
        |||
        Часть 3: Опиши ризики за регіонами (фокус на топ-3).

        Не використовуй Markdown розмітку, поверни тільки чистий текст із роздільниками.
        """

        try:
            response = self.client.models.generate_content(
                model=self.model_name, contents=prompt
            )
            raw_text = response.text.strip()

            # Split raw response string into a list using the custom token delimiter
            parts = [part.strip() for part in raw_text.split("|||")]

            # Fallback mechanism if the AI fails to generate enough sections
            while len(parts) < 3:
                parts.append(
                    "Аналітика для цього розділу відсутня або згенерована некоректно."
                )

            self.ai_analytics_parts = parts[:3]
            print(">>> Аналітика успішно згенерована та розбита за графіками!")
        except Exception as e:
            print(f"      Помилка генерації ІІ: {e}")
            self.ai_analytics_parts = ["Помилка API"] * 3

    def create_pdf_report(self):
        # PDF Report Compilation via fpdf2
        print(">>> Формування та збереження PDF-звіту...")

        pdf = FPDF()
        # Enable automatic page breaks with a bottom margin of 15mm
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Load system fonts supporting Cyrillic characters
        font_path_reg = r"C:\Windows\Fonts\arial.ttf"
        font_path_bold = r"C:\Windows\Fonts\arialbd.ttf"
        pdf.add_font("Arial", "", font_path_reg)
        pdf.add_font("Arial", "B", font_path_bold)

        # === Document Title and Metadata Section ===
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, "AI-Звіт: Аналіз Часових Рядів (Повітряні тривоги)", align="C")
        pdf.ln(15)

        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "Ключові метрики датасету:")
        pdf.ln(8)

        pdf.set_font("Arial", "", 11)
        pdf.cell(
            0, 6, f"• Період: {self.metrics['start_date']} — {self.metrics['end_date']}"
        )
        pdf.ln(6)
        pdf.cell(0, 6, f"• Всього тривог у вибірці: {self.metrics['total_records']}")
        pdf.ln(6)
        pdf.cell(
            0, 6, f"• Найбільш навантажені регіони: {self.metrics['top_3_regions']}"
        )
        pdf.ln(15)

        # === Section 1: EDA Chart + EDA Text ===
        # Page budget check: EDA chart requires around 120mm of space
        if pdf.get_y() > 150:
            pdf.add_page()

        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "1. Динаміка у часі (EDA)", ln=True)

        pdf.image(self.images_paths["eda"], w=190)
        pdf.ln(5)

        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, self.ai_analytics_parts[0])
        pdf.ln(15)

        # === Section 2: Decomposition Chart + Decomposition Text ===
        # Page budget check: Large decomposition plot requires at least 170mm of space
        if pdf.get_y() > 100:
            pdf.add_page()

        pdf.set_font("Arial", "B", 12)
        pdf.cell(
            0, 10, "2. Декомпозиція Часового Ряду (Тренд, Сезонність, Шум)", ln=True
        )

        pdf.image(self.images_paths["decomp"], w=190)
        pdf.ln(5)

        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, self.ai_analytics_parts[1])
        pdf.ln(15)

        # === Section 3: Regional Risk Chart + Risk Text ===
        # Page budget check: Risk barplot requires around 130mm of space
        if pdf.get_y() > 140:
            pdf.add_page()

        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "3. Аналіз Ризиків за Регіонами", ln=True)

        pdf.image(self.images_paths["risk"], w=190)
        pdf.ln(5)

        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, self.ai_analytics_parts[2])

        # Save finalized PDF file to disk
        output_filename = "AI_Time_Series_Report.pdf"
        pdf.output(output_filename)
        print(
            f"Звіт успішно збережено в директорії програми: "
            f"{os.path.abspath(output_filename)}"
        )

        # Remove temporary image files from storage
        for path in self.images_paths.values():
            if os.path.exists(path):
                os.remove(path)

    def run_analysis(self):
        # Orchestrator running the continuous execution pipeline
        self.load_and_clean_data()
        self.prepare_time_series()
        self.plot_eda()
        self.perform_decomposition()
        self.test_stationarity()
        self.plot_risk_profile()
        self.generate_ai_analytics()
        self.create_pdf_report()


if __name__ == "__main__":
    GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
    if not GEMINI_API_KEY:
        print("УВАГА: Ключ GEMINI_API_KEY не знайдено в змінних оточення.")
    else:
        print("API Ключ успішно завантажено.")

    analyzer = AirRaidAnalyzer(
        alerts_path="data/official_data_en.csv",
        risk_path="data/region_risk.csv",
        gemini_api_key=GEMINI_API_KEY,
    )
    analyzer.run_analysis()
